package io.chillplus;

import io.chillplus.model.TvShow;

import javax.validation.Valid;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicLong;

@Path("/api/tv")
public class TvShowResource {

    //List<TvShow> tvShows = new ArrayList<>();
    private Set<TvShow> tvShows = Collections.newSetFromMap(Collections.synchronizedMap(new LinkedHashMap<>()));

    private final AtomicLong counter = new AtomicLong();

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Set<TvShow> getAll() {
        return tvShows;
    }

    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.APPLICATION_JSON)
    public Response create(@Valid TvShow tvShow) {
        //System.out.println(tvShow);
        if (tvShow.getId() != null) {
            return Response.status(Response.Status.BAD_REQUEST).entity("ID must be autogenerated").build();
        }

        tvShow.setId(counter.incrementAndGet());
        tvShows.add(tvShow);
        return Response.status(Response.Status.CREATED).entity(tvShow).build();
    }
}
